import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer7";

import { Inter_Tight, Inter } from "next/font/google";

const inter_tight = Inter_Tight({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--display-family",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--text-family",
});

export const metadata = {
  title: "Laurem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className="scroll-smooth">
      <body className={`${inter_tight.variable} ${inter.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
